/* NextPlay Kids — product catalogue (45 products) + program/camp data */
(function () {
  'use strict';

  var SPORTS = ['Football', 'Cricket', 'Basketball', 'Tennis', 'Badminton', 'Volleyball', 'Baseball/Softball', 'Hockey', 'Rugby', 'Athletics', 'Swimming', 'Cycling', 'Skating', 'Martial Arts', 'Gymnastics', 'Dance & Cheer', 'Table Tennis', 'Archery', 'Adventure/Outdoor'];

  function P(o) { return o; }
  var PRODUCTS = [
    /* --- Football --- */
    P({ id: 'p01', name: 'Junior Strike Football Size 3', cat: 'A', catName: 'Sport Equipment', sport: 'Football', age: [5, 9], lvl: 'Beginner', price: 749, mrp: 999, rating: 4.7, rc: 412, colors: ['#2E7D32', '#FFFFFF', '#0A1128'], sizes: ['Size 3'], emoji: '⚽', hue: 140, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Machine-stitched TPU ball tuned for smaller feet. Soft touch cover keeps control easy for first-time players, holds air through a full season of park sessions.', notes: 'Size 3 is the official junior size for under-10 football. Pair with shin guards for match play.' }),
    P({ id: 'p02', name: 'Pro Grip Match Football Size 5', cat: 'A', catName: 'Sport Equipment', sport: 'Football', age: [12, 17], lvl: 'Advanced', price: 1899, mrp: 2499, rating: 4.8, rc: 268, colors: ['#0A1128', '#FF6A3D'], sizes: ['Size 5'], emoji: '⚽', hue: 214, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'FIFA Basic Quality match ball with textured PU casing and butyl bladder. Consistent flight in monsoon-damp conditions.', notes: 'Official size 5 for 12+ players. Check pressure weekly (0.8–1.0 bar).' }),
    P({ id: 'p03', name: 'Kids Shin Guards with Ankle Sleeve', cat: 'B', catName: 'Safety Gear', sport: 'Football', age: [6, 14], lvl: 'All Levels', price: 649, mrp: 899, rating: 4.6, rc: 351, colors: ['#0A1128', '#00E676'], sizes: ['S', 'M', 'L'], emoji: '🛡️', hue: 160, safe: 'CE', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Impact-EVA shell with breathable compression sleeve. Stays put through 90 minutes of sliding tackles.', notes: 'Measure shin length knee-to-ankle and pick the closest size — see Safety & Sizing guide.' }),
    P({ id: 'p04', name: 'Academy Turf Boots JR', cat: 'C', catName: 'Sportswear', sport: 'Football', age: [8, 14], lvl: 'Intermediate', price: 2299, mrp: 2999, rating: 4.5, rc: 189, colors: ['#00E676', '#0A1128', '#FF6A3D'], sizes: ['UK 1', 'UK 2', 'UK 3', 'UK 4', 'UK 5'], emoji: '👟', hue: 200, safe: 'ISO', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Lightweight synthetic upper with rubber turf studs for grip on wet Mumbai monsoon turf. Padded heel counter protects growing ankles.', notes: 'Leave a thumb-width of toe room; feet grow fast at this age — re-measure every 4 months.' }),
    /* --- Cricket --- */
    P({ id: 'p05', name: 'Kashmir Willow Cricket Bat — Size 5', cat: 'A', catName: 'Sport Equipment', sport: 'Cricket', age: [8, 11], lvl: 'Beginner', price: 1699, mrp: 2199, rating: 4.6, rc: 523, colors: ['#C8A254'], sizes: ['Size 5'], emoji: '🏏', hue: 42, safe: 'ISO', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Hand-picked Kashmir willow with cane handle. Pre-knocked so it is match-ready out of the box — no waiting weeks.', notes: 'Size 5 suits heights 130–140 cm. Bat should reach the child’s hip bone when placed toe-down.' }),
    P({ id: 'p06', name: 'Cricket Starter Set — Bat, Ball & Stumps', cat: 'A', catName: 'Sport Equipment', sport: 'Cricket', age: [5, 10], lvl: 'Beginner', price: 1399, mrp: 1899, rating: 4.7, rc: 610, colors: ['#C8A254', '#0A1128'], sizes: ['Size 3', 'Size 5'], emoji: '🏏', hue: 46, safe: 'ISO', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Everything for a first gully-cricket summer: soft-certified ball, light willow bat and spring-back plastic stumps.', notes: 'Soft ball variant is safe for terraces and short-pitch games without pads.' }),
    P({ id: 'p07', name: 'Junior Cricket Helmet — Steel Grill', cat: 'B', catName: 'Safety Gear', sport: 'Cricket', age: [8, 15], lvl: 'All Levels', price: 1999, mrp: 2599, rating: 4.8, rc: 297, colors: ['#0A1128', '#2E7D32'], sizes: ['S', 'M', 'L'], emoji: '🪖', hue: 210, safe: 'BS 7928', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'BS 7928:2012 certified junior helmet with titanium-grade grill and moisture-wicking liner. Non-negotiable for hard-ball net sessions.', notes: 'Grill should sit two fingers below the eye line. See fit guide before first use.' }),
    P({ id: 'p08', name: 'Cricket Batting Gloves — Youth', cat: 'B', catName: 'Safety Gear', sport: 'Cricket', age: [7, 14], lvl: 'Intermediate', price: 899, mrp: 1199, rating: 4.4, rc: 176, colors: ['#FFFFFF', '#0A1128'], sizes: ['Boys', 'Youth', 'Junior'], sizing: 'hands', emoji: '🧤', hue: 30, safe: 'CE', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Cotton-padded finger bolsters with sheep-leather palm. Flexible enough for small hands to grip the handle properly.', notes: 'Fingers should reach within 1 cm of glove tips — crushed fingertips are the most common cricket injury.' }),
    /* --- Basketball --- */
    P({ id: 'p09', name: 'All-Surface Basketball Size 5', cat: 'A', catName: 'Sport Equipment', sport: 'Basketball', age: [7, 11], lvl: 'Beginner', price: 899, mrp: 1199, rating: 4.6, rc: 388, colors: ['#FF6A3D', '#0A1128'], sizes: ['Size 5'], emoji: '🏀', hue: 24, safe: 'EN 71', eco: false, ind: 'both', team: true, sustain: false, desc: 'Deep-channel composite ball with grippy rubber cover for concrete courts and wooden gyms alike.', notes: 'Size 5 (27.5") is the junior standard for under-12; moves to size 6/7 at 12+.' }),
    P({ id: 'p10', name: 'Grip Training Basketball Size 6', cat: 'A', catName: 'Sport Equipment', sport: 'Basketball', age: [12, 14], lvl: 'Intermediate', price: 1249, mrp: 1599, rating: 4.5, rc: 201, colors: ['#00E676', '#0A1128'], sizes: ['Size 6'], emoji: '🏀', hue: 150, safe: 'EN 71', eco: false, ind: 'both', team: true, sustain: false, desc: 'Intermediate-weight composite leather ball for developing shooting form and crossover control.', notes: 'Girls 12+ and boys 12–13 standard; full size 7 from 14+ for boys.' }),
    P({ id: 'p11', name: 'Adjustable Basketball Ring & Net Set', cat: 'A', catName: 'Sport Equipment', sport: 'Basketball', age: [5, 14], lvl: 'All Levels', price: 3499, mrp: 4499, rating: 4.7, rc: 143, colors: ['#FF6A3D'], sizes: ['Wall-mount'], emoji: '🥅', hue: 18, safe: 'ISO', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Height adjusts 2.2 m to 3.05 m so the whole family can shoot at their level. Weatherproof steel with all-weather net.', notes: 'Mount height per youngest player, then raise as they grow — dunking a too-high rim kills form.' }),
    /* --- Tennis --- */
    P({ id: 'p12', name: 'Junior Tennis Racket 23"', cat: 'A', catName: 'Sport Equipment', sport: 'Tennis', age: [5, 8], lvl: 'Beginner', price: 1299, mrp: 1699, rating: 4.6, rc: 342, colors: ['#00E676', '#FFFFFF'], sizes: ['23 inch'], emoji: '🎾', hue: 120, safe: 'EN 71', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Aluminium 23" frame at just 205 g — light enough for a five-year-old to swing all session without wrist strain.', notes: 'Racket should reach from floor to child’s mid-forearm when held upside-down.' }),
    P({ id: 'p13', name: 'Junior Tennis Racket 26" + Cover', cat: 'A', catName: 'Sport Equipment', sport: 'Tennis', age: [9, 12], lvl: 'Intermediate', price: 1899, mrp: 2399, rating: 4.7, rc: 218, colors: ['#0A1128', '#FFC64D'], sizes: ['26 inch'], emoji: '🎾', hue: 210, safe: 'EN 71', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Graphite-composite 26" with vibration-damping handle. The transition racket before full-size frames.', notes: '26" suits ages 9–10 per ITF playbook; 27" adult frames from 12–13.' }),
    P({ id: 'p14', name: 'Stage 2 Low-Compression Tennis Balls (3-pack)', cat: 'A', catName: 'Sport Equipment', sport: 'Tennis', age: [7, 10], lvl: 'Beginner', price: 549, mrp: 699, rating: 4.8, rc: 455, colors: ['#FF6A3D'], sizes: ['Stage 2'], emoji: '🟠', hue: 20, safe: 'EN 71', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Orange-dot balls bounce 50% lower, giving kids time to set feet and swing properly instead of flinching.', notes: 'Use Stage 3 (red) for under-7, Stage 2 (orange) for 7–9, Stage 1 (green) for 9–10.' }),
    /* --- Badminton --- */
    P({ id: 'p15', name: 'Featherweight Badminton Racket Set (2)', cat: 'A', catName: 'Sport Equipment', sport: 'Badminton', age: [6, 12], lvl: 'Beginner', price: 1099, mrp: 1499, rating: 4.5, rc: 512, colors: ['#00E676', '#FF6A3D'], sizes: ['Short'], emoji: '🏸', hue: 130, safe: 'EN 71', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Two 78 g steel-shaft rackets with padded grips — sized for junior hands, tough enough for terrace rallies.', notes: 'Keep grip size G4 for juniors; lighter head = faster learning of serve motion.' }),
    P({ id: 'p16', name: 'Nylon Shuttlecocks Tube (6-pack)', cat: 'A', catName: 'Sport Equipment', sport: 'Badminton', age: [6, 15], lvl: 'All Levels', price: 349, mrp: 449, rating: 4.3, rc: 289, colors: ['#FFFFFF'], sizes: ['Medium'], emoji: '🪶', hue: 0, safe: 'EN 71', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Stable-flight nylon shuttles that survive hundreds of terrace rallies without fraying.', notes: 'White shuttles on green mats, yellow on wooden floors — visibility matters for young eyes.' }),
    /* --- Volleyball --- */
    P({ id: 'p17', name: 'Soft-Touch Volleyball Size 4', cat: 'A', catName: 'Sport Equipment', sport: 'Volleyball', age: [7, 11], lvl: 'Beginner', price: 849, mrp: 1099, rating: 4.4, rc: 167, colors: ['#00E676', '#0A1128'], sizes: ['Size 4'], emoji: '🏐', hue: 140, safe: 'EN 71', eco: false, ind: 'both', team: true, sustain: false, desc: 'Reduced-pressure foam-back ball that does not sting forearms while kids learn the platform pass.', notes: 'Size 4 lighter ball for under-11; forearm soreness is a weight problem, not a technique one.' }),
    P({ id: 'p18', name: 'Beach Volleyball — All-Weather', cat: 'A', catName: 'Sport Equipment', sport: 'Volleyball', age: [12, 17], lvl: 'Intermediate', price: 1199, mrp: 1599, rating: 4.5, rc: 98, colors: ['#FFC64D', '#FFFFFF'], sizes: ['Size 5'], emoji: '🏖️', hue: 40, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Sand-resistant composite cover for Juhu-beach rallies and school court alike.', notes: '' }),
    /* --- Baseball --- */
    P({ id: 'p19', name: 'T-Ball Starter Set — Bat, Ball & Tee', cat: 'A', catName: 'Sport Equipment', sport: 'Baseball/Softball', age: [4, 8], lvl: 'Beginner', price: 1599, mrp: 2099, rating: 4.6, rc: 233, colors: ['#FFFFFF', '#0A1128'], sizes: ['One Size'], emoji: '⚾', hue: 210, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Adjustable tee grows from knee to waist height; foam-safe ball and light alloy bat for confident first swings.', notes: 'Tee-ball is the safest entry to bat sports — no pitched balls before age 8.' }),
    P({ id: 'p20', name: 'Junior Baseball Glove 10.5"', cat: 'A', catName: 'Sport Equipment', sport: 'Baseball/Softball', age: [7, 12], lvl: 'Beginner', price: 1349, mrp: 1799, rating: 4.4, rc: 154, colors: ['#8B4513'], sizes: ['10.5 inch'], emoji: '🧤', hue: 28, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Pre-broken-in PU leather pocket that actually closes around the ball for young hands.', notes: 'Glove should close fully when squeezing with the non-throwing hand.' }),
    /* --- Hockey --- */
    P({ id: 'p21', name: 'Composite Junior Hockey Stick 32"', cat: 'A', catName: 'Sport Equipment', sport: 'Hockey', age: [8, 13], lvl: 'Intermediate', price: 2199, mrp: 2899, rating: 4.6, rc: 121, colors: ['#0A1128', '#00E676'], sizes: ['32 inch'], emoji: '🏑', hue: 200, safe: 'FIH', eco: false, ind: 'outdoor', team: true, sustain: false, desc: '30% carbon composite with maxi head — the sweet spot of power and control for growing players.', notes: 'Stick to hip height when toe-down; too-long sticks force dangerous reaching posture.' }),
    P({ id: 'p22', name: 'Hockey Shin Guard & Glove Combo', cat: 'B', catName: 'Safety Gear', sport: 'Hockey', age: [8, 14], lvl: 'All Levels', price: 999, mrp: 1299, rating: 4.5, rc: 87, colors: ['#0A1128'], sizes: ['S', 'M'], emoji: '🛡️', hue: 220, safe: 'CE', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'CE-marked shin guards plus left-hand glove — the mandatory protective pair for junior turf hockey.', notes: 'Always wear both; one-handed protection still leaves the leading hand exposed.' }),
    /* --- Rugby --- */
    P({ id: 'p23', name: 'Grip Trainer Rugby Ball Size 4', cat: 'A', catName: 'Sport Equipment', sport: 'Rugby', age: [7, 11], lvl: 'Beginner', price: 949, mrp: 1249, rating: 4.4, rc: 76, colors: ['#0A1128', '#FF6A3D'], sizes: ['Size 4'], emoji: '🏉', hue: 20, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Supergrip pimpled rubber surface for wet-grass handling; size 4 eases the pass before the size-5 jump at 12.', notes: 'Tag rugby (no tackle) is the only format for under-8s.' }),
    /* --- Athletics --- */
    P({ id: 'p24', name: 'Junior Running Spikes', cat: 'C', catName: 'Sportswear', sport: 'Athletics', age: [10, 15], lvl: 'Intermediate', price: 2499, mrp: 3199, rating: 4.5, rc: 132, colors: ['#00E676', '#0A1128', '#FF6A3D'], sizes: ['UK 2', 'UK 3', 'UK 4', 'UK 5', 'UK 6'], emoji: '👟', hue: 150, safe: 'ISO', eco: false, ind: 'outdoor', team: false, sustain: false, desc: '6-pin rubber spike plate with cushioned midsole — proper track grip without punishing young joints on hard Indian tracks.', notes: 'Only for track use; never road. Start with 6 mm blanks, not spikes.' }),
    P({ id: 'p25', name: 'Kids Agility Cone Set (12) + Ladder', cat: 'D', catName: 'Training Aids', sport: 'Athletics', age: [5, 14], lvl: 'All Levels', price: 999, mrp: 1399, rating: 4.7, rc: 421, colors: ['#FF6A3D', '#00E676'], sizes: ['One Set'], emoji: '🚥', hue: 16, safe: 'EN 71', eco: false, ind: 'both', team: true, sustain: false, desc: '12 crush-proof cones plus a 4 m flat-rung ladder — the full warm-up circuit for any junior athlete.', notes: 'Every academy starter bundle includes this set.' }),
    P({ id: 'p26', name: 'Soft Relay Baton Set (4)', cat: 'A', catName: 'Sport Equipment', sport: 'Athletics', age: [6, 14], lvl: 'Beginner', price: 449, mrp: 599, rating: 4.3, rc: 64, colors: ['#00E676', '#FF6A3D', '#FFC64D', '#5AB8FF'], sizes: ['One Size'], emoji: '🤝', hue: 130, safe: 'EN 71', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Grippy ABS batons in team colours — makes every school sports-day relay feel official.', notes: '' }),
    /* --- Swimming --- */
    P({ id: 'p27', name: 'Anti-Fog Junior Swim Goggles', cat: 'B', catName: 'Safety Gear', sport: 'Swimming', age: [4, 12], lvl: 'All Levels', price: 599, mrp: 799, rating: 4.6, rc: 578, colors: ['#5AB8FF', '#00E676', '#0A1128'], sizes: ['Junior'], emoji: '🥽', hue: 200, safe: 'CE', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Silicone-seal goggles with UV-blocking, anti-fog lenses. Adjusts without pulling hair — a surprisingly big deal for kids.', notes: 'A good seal holds for a 5-count when pressed without straps.' }),
    P({ id: 'p28', name: 'Kids Floatation Vest 20–30 kg', cat: 'B', catName: 'Safety Gear', sport: 'Swimming', age: [3, 8], lvl: 'Beginner', price: 1299, mrp: 1699, rating: 4.8, rc: 342, colors: ['#FF6A3D', '#5AB8FF'], sizes: ['20–30 kg'], emoji: '🦺', hue: 16, safe: 'ISO 12402', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'ISO 12402-5 certified buoyancy aid with grab handle and crotch strap so it can never slip off.', notes: 'Buoyancy aid (not arm bands) for open water. Adult within arm’s reach — always.' }),
    P({ id: 'p29', name: 'Quick-Dry Swim Kit — Goggles + Cap + Bag', cat: 'A', catName: 'Sport Equipment', sport: 'Swimming', age: [5, 12], lvl: 'Beginner', price: 899, mrp: 1149, rating: 4.5, rc: 219, colors: ['#5AB8FF', '#00E676'], sizes: ['Junior'], emoji: '🏊', hue: 205, safe: 'CE', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Pool-day bundle: anti-fog goggles, silicone cap and mesh drain bag that actually dries between sessions.', notes: '' }),
    /* --- Cycling --- */
    P({ id: 'p30', name: 'Kids Bike Helmet 50–56 cm', cat: 'B', catName: 'Safety Gear', sport: 'Cycling', age: [5, 12], lvl: 'All Levels', price: 1499, mrp: 1999, rating: 4.8, rc: 631, colors: ['#00E676', '#FF6A3D', '#0A1128'], sizes: ['50–56 cm'], emoji: '🪖', hue: 140, safe: 'CPSC', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'CPSC-certified in-mold helmet, 270 g, with dial-fit ring and rear LED. The single most important piece of gear we sell.', notes: 'Two-finger rule: helmet brim two fingers above eyebrows, straps two fingers under chin. See fit guide.' }),
    P({ id: 'p31', name: '16" Steel Frame Kids Cycle', cat: 'A', catName: 'Sport Equipment', sport: 'Cycling', age: [4, 7], lvl: 'Beginner', price: 5999, mrp: 7499, rating: 4.6, rc: 187, colors: ['#00E676', '#FF6A3D'], sizes: ['16 inch'], emoji: '🚲', hue: 130, safe: 'ISO', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Training-wheel-ready steel frame with full chain guard, caliper brakes sized for small hands and cushioned saddle.', notes: 'Both feet flat on the ground while seated = right size. Raise saddle as confidence grows.' }),
    P({ id: 'p32', name: 'Protective Pad Set — Knee/Elbow/Wrist', cat: 'B', catName: 'Safety Gear', sport: 'Skating', age: [4, 14], lvl: 'All Levels', price: 799, mrp: 1099, rating: 4.7, rc: 498, colors: ['#0A1128', '#00E676'], sizes: ['S', 'M', 'L'], emoji: '🛡️', hue: 220, safe: 'CE', eco: false, ind: 'both', team: false, sustain: false, desc: '6-piece CE pad set with impact-EVA caps and elastic straps. The non-negotiable trio for wheels of any kind.', notes: 'Wrist guards are the #1 skating injury preventer — never skip them.' }),
    /* --- Skating --- */
    P({ id: 'p33', name: 'Adjustable Inline Skates (UK 12–3)', cat: 'A', catName: 'Sport Equipment', sport: 'Skating', age: [6, 12], lvl: 'Beginner', price: 2999, mrp: 3999, rating: 4.6, rc: 276, colors: ['#00E676', '#0A1128'], sizes: ['Adjustable UK 12–3'], emoji: '🛼', hue: 150, safe: 'EN 71', eco: false, ind: 'both', team: false, sustain: false, desc: 'Four-size adjustable boot with ABEC-7 bearings and brake — grows through three shoe sizes for years of use.', notes: 'Skates should feel snug like boots, not loose like shoes. Always pair with pad set + helmet.' }),
    /* --- Martial Arts --- */
    P({ id: 'p34', name: 'Kids Karate Gi Uniform with Belt', cat: 'C', catName: 'Sportswear', sport: 'Martial Arts', age: [5, 13], lvl: 'Beginner', price: 1199, mrp: 1599, rating: 4.7, rc: 312, colors: ['#FFFFFF'], sizes: ['110 cm', '120 cm', '130 cm', '140 cm'], emoji: '🥋', hue: 0, safe: 'ISO', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Brushed cotton-poly gi that survives the wash and the tatami. White belt included.', notes: 'Gi length to mid-forearm/mid-calf; sleeve rolled back = too big.' }),
    P({ id: 'p35', name: 'Sparring Head Guard — Junior', cat: 'B', catName: 'Safety Gear', sport: 'Martial Arts', age: [8, 15], lvl: 'Intermediate', price: 1499, mrp: 1999, rating: 4.6, rc: 143, colors: ['#0A1128', '#FF6A3D'], sizes: ['S', 'M', 'L'], emoji: '🪖', hue: 220, safe: 'CE', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'CE-certified padded head guard for controlled sparring from blue-belt level upward.', notes: 'Contact sparring only with head guard, certified instructor present, and parental consent on file.' }),
    /* --- Gymnastics --- */
    P({ id: 'p36', name: 'Junior Gymnastics Grip & Wrist Support', cat: 'B', catName: 'Safety Gear', sport: 'Gymnastics', age: [7, 14], lvl: 'Intermediate', price: 899, mrp: 1199, rating: 4.5, rc: 128, colors: ['#FFFFFF', '#00E676'], sizes: ['XS', 'S', 'M'], emoji: '🤸', hue: 0, safe: 'CE', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Dowelled palm grips that protect young wrists during bar work without limiting the swing.', notes: 'Grips only under coach supervision — they change bar feel and need a learn-in period.' }),
    P({ id: 'p37', name: 'Balance Beam Home Practice Mat', cat: 'A', catName: 'Sport Equipment', sport: 'Gymnastics', age: [5, 12], lvl: 'Beginner', price: 3299, mrp: 4199, rating: 4.6, rc: 97, colors: ['#00E676'], sizes: ['8 ft'], emoji: '🤸', hue: 130, safe: 'EN 71', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Low 12 cm foam beam on a fold-flat base — living-room confidence for walkers and handstands alike.', notes: 'Use on non-slip surface only; adult supervision for under-6.' }),
    /* --- Dance --- */
    P({ id: 'p38', name: 'Cheer & Dance Practice Set — Pom + Ribbon', cat: 'A', catName: 'Sport Equipment', sport: 'Dance & Cheer', age: [5, 12], lvl: 'Beginner', price: 649, mrp: 899, rating: 4.5, rc: 231, colors: ['#FF6A3D', '#00E676', '#FFC64D'], sizes: ['One Size'], emoji: '🎉', hue: 16, safe: 'EN 71', eco: false, ind: 'indoor', team: true, sustain: false, desc: 'Soft-handle poms and a flowing rhythm ribbon — the starter kit for school-day dance sessions.', notes: '' }),
    P({ id: 'p39', name: 'Grip Socks for Studio & Gym', cat: 'C', catName: 'Sportswear', sport: 'Dance & Cheer', age: [3, 12], lvl: 'All Levels', price: 399, mrp: 549, rating: 4.4, rc: 189, colors: ['#FFFFFF', '#00E676', '#FF6A3D'], sizes: ['XS', 'S', 'M'], emoji: '🧦', hue: 0, safe: 'ISO', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Silicone-dot soles that stop slips on polished studio floors and trampoline parks.', notes: '' }),
    /* --- Table Tennis --- */
    P({ id: 'p40', name: 'Junior Table Tennis Racket Pair + Balls', cat: 'A', catName: 'Sport Equipment', sport: 'Table Tennis', age: [6, 14], lvl: 'Beginner', price: 999, mrp: 1349, rating: 4.5, rc: 267, colors: ['#FF6A3D', '#0A1128'], sizes: ['One Size'], emoji: '🏓', hue: 16, safe: 'EN 71', eco: false, ind: 'indoor', team: true, sustain: false, desc: 'Shakehand rackets with flared junior handles, 1.5 mm sponge and three 40 mm training balls.', notes: '' }),
    /* --- Archery --- */
    P({ id: 'p41', name: 'Beginner Recurve Bow Set 12 lb', cat: 'A', catName: 'Sport Equipment', sport: 'Archery', age: [8, 14], lvl: 'Beginner', price: 3799, mrp: 4799, rating: 4.7, rc: 154, colors: ['#0A1128', '#00E676'], sizes: ['Right Hand', 'Left Hand'], emoji: '🏹', hue: 210, safe: 'ISO', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Fibreglass-limb recurve at a forgiving 12 lb draw with suction-tip target arrows and arm guard.', notes: 'Certified range + instructor only; left-hand variant for left-eye-dominant archers.' }),
    /* --- Adventure --- */
    P({ id: 'p42', name: 'Kids Trek Daypack 12 L', cat: 'A', catName: 'Sport Equipment', sport: 'Adventure/Outdoor', age: [6, 13], lvl: 'All Levels', price: 1099, mrp: 1499, rating: 4.6, rc: 176, colors: ['#00E676', '#FF6A3D'], sizes: ['12 L'], emoji: '🎒', hue: 140, safe: 'ISO', eco: false, ind: 'outdoor', team: false, sustain: false, desc: 'Reflective-trim daypack with whistle-buckle, rain cover and a 12 L limit — small enough that kids carry their own load properly.', notes: 'Pack no more than 10% of body weight on treks.' }),
    P({ id: 'p43', name: 'Junior Camping Headlamp', cat: 'D', catName: 'Training Aids', sport: 'Adventure/Outdoor', age: [5, 14], lvl: 'All Levels', price: 649, mrp: 899, rating: 4.4, rc: 88, colors: ['#FFC64D'], sizes: ['One Size'], emoji: '🔦', hue: 40, safe: 'CE', eco: false, ind: 'outdoor', team: false, sustain: false, desc: '120-lumen headlamp with tilt beam and breakaway strap — camp-night favourite.', notes: '' }),
    P({ id: 'p44', name: 'Kids Hydration Bottle 500 ml (Sip-Free Lid)', cat: 'D', catName: 'Training Aids', sport: 'Adventure/Outdoor', age: [4, 14], lvl: 'All Levels', price: 549, mrp: 749, rating: 4.7, rc: 356, colors: ['#00E676', '#5AB8FF', '#FF6A3D'], sizes: ['500 ml'], emoji: '🧴', hue: 140, safe: 'BPA-free', eco: true, ind: 'both', team: false, sustain: true, desc: 'Leak-proof, BPA-free, one-hand sip lid with a carry loop that clips to any daypack.', notes: 'Sip every 15–20 minutes on the field — thirst arrives late in kids.' }),
    /* --- Recovery, digital, programs --- */
    P({ id: 'p45', name: 'Junior Muscle-Roller & Stretch Strap Kit', cat: 'E', catName: 'Recovery & Care', sport: 'Athletics', age: [10, 17], lvl: 'All Levels', price: 1299, mrp: 1699, rating: 4.5, rc: 112, colors: ['#00E676'], sizes: ['One Kit'], emoji: '🧘', hue: 130, safe: 'ISO', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Foam roller + stretching strap with a printed junior cool-down routine designed with a paediatric physiotherapist.', notes: 'Recovery is a wellness habit, not medical treatment — see our wellness note in Safety & Sizing.' }),
    P({ id: 'p46', name: 'NextPlay At-Home Drills — 12-Week Video Pass', cat: 'F', catName: 'Digital Programs', sport: 'Athletics', age: [6, 14], lvl: 'All Levels', price: 999, mrp: 1499, rating: 4.6, rc: 203, colors: ['#00E676'], sizes: ['12 Weeks'], emoji: '📱', hue: 160, safe: 'Digital', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Coach-led 15-minute daily drill videos for any sport, tracked on a printable progress chart.', notes: 'Screen time you can feel good about — it ends with them going outside.' }),
    P({ id: 'p47', name: 'Multi-Sport Starter Classes — Monthly (8 sessions)', cat: 'G', catName: 'Programs', sport: 'Athletics', age: [4, 7], lvl: 'Beginner', price: 3200, mrp: 4000, rating: 4.9, rc: 341, colors: ['#00E676'], sizes: ['Monthly'], emoji: '🌟', hue: 150, safe: 'Coached', eco: false, ind: 'indoor', team: true, sustain: false, desc: 'Eight weekend sessions sampling football, gymnastics, athletics and games across Andheri & Powai venues.', notes: 'Coach:child ratio 1:8. First session is a free trial with parental consent on arrival.' }),
    P({ id: 'p48', name: 'Football Academy — Monthly (12 sessions)', cat: 'G', catName: 'Programs', sport: 'Football', age: [8, 15], lvl: 'Intermediate', price: 4500, mrp: 5000, rating: 4.8, rc: 289, colors: ['#0A1128'], sizes: ['Monthly'], emoji: '⚽', hue: 210, safe: 'Coached', eco: false, ind: 'outdoor', team: true, sustain: false, desc: 'Three evenings a week at our Andheri turf with UEFA-licensed coaches, plus a monthly match day.', notes: '' }),
    P({ id: 'p49', name: 'Swim Level-1 Course (10 sessions)', cat: 'G', catName: 'Programs', sport: 'Swimming', age: [4, 9], lvl: 'Beginner', price: 5500, mrp: 6500, rating: 4.9, rc: 412, colors: ['#5AB8FF'], sizes: ['Course'], emoji: '🏊', hue: 205, safe: 'Coached', eco: false, ind: 'indoor', team: false, sustain: false, desc: 'Water-confidence to independent 10 m swim, max 1:4 coach ratio, heated pool at Powai.', notes: '' }),
    P({ id: 'p50', name: 'Girls’ Confidence Program — 6 Weeks', cat: 'G', catName: 'Programs', sport: 'Dance & Cheer', age: [9, 14], lvl: 'All Levels', price: 2800, mrp: 3500, rating: 4.9, rc: 167, colors: ['#FF6A3D', '#00E676'], sizes: ['6 Weeks'], emoji: '💪', hue: 16, safe: 'Coached', eco: false, ind: 'indoor', team: true, sustain: false, desc: 'Movement, team games and mentor circles building body confidence and voice — no aesthetic scoring, ever.', notes: 'Female-led sessions; mixed-sport rotation each week.' })
  ];

  /* trim catalogue to 45 products with all 7 categories represented (A–G) */
  var drop = { p18: 1, p20: 1, p26: 1, p29: 1, p39: 1 };
  for (var di = PRODUCTS.length - 1; di >= 0; di--) {
    if (drop[PRODUCTS[di].id]) PRODUCTS.splice(di, 1);
  }

  var CATS = {
    A: 'Sport Equipment', B: 'Safety Gear', C: 'Sportswear',
    D: 'Training Aids', E: 'Recovery & Care', F: 'Digital Programs', G: 'Programs'
  };

  var AGES = [
    { id: 'tiny', label: 'Tiny Movers', range: '2–4 yrs', num: [2, 4], glyph: '🧒', focus: 'Balance, coordination and the pure joy of moving. Everything here is soft, light and safe to tumble with.', sports: 'Soft play, tumbling, water familiarisation, first-ball games' },
    { id: 'little', label: 'Little Athletes', range: '5–7 yrs', num: [5, 7], glyph: '🏃', focus: 'Fundamental skills: run, jump, throw, catch. Confidence grows with every small win.', sports: 'Football, gymnastics, swimming, athletics basics' },
    { id: 'rising', label: 'Rising Players', range: '8–11 yrs', num: [8, 11], glyph: '🤾', focus: 'Learning the game — rules, teamwork and their first competitive sparkle.', sports: 'Cricket, basketball, tennis, badminton, skating' },
    { id: 'young', label: 'Young Competitors', range: '12–14 yrs', num: [12, 14], glyph: '🏅', focus: 'Structured training, position skills and healthy competition with strong safety habits.', sports: 'Academies, athletics, swimming squads, martial arts' },
    { id: 'future', label: 'Future Champions', range: '15–17 yrs', num: [15, 17], glyph: '🏆', focus: 'Performance mindset, recovery discipline and leadership on and off the field.', sports: 'Elite programs, coaching-assist pathways, strength foundations' }
  ];

  var PROGRAMS = [
    { id: 'g1', title: 'Multi-Sport Starter Classes', glyph: '🌟', age: '4–7 yrs', when: 'Sat–Sun · 9 AM', price: 3200, venue: 'Andheri West & Powai', ratio: '1:8 coach ratio', tint: 150, desc: 'One season, four sports. Kids sample football, gymnastics, athletics and team games to find what they love.' },
    { id: 'g2', title: 'Football Academy', glyph: '⚽', age: '8–15 yrs', when: 'Mon–Wed–Fri · 5:30 PM', price: 4500, venue: 'Andheri Sports Complex', ratio: 'UEFA-licensed coaches', tint: 210, desc: 'Technical foundations, small-sided matches and a monthly game day on floodlit turf.' },
    { id: 'g3', title: 'Cricket Academy', glyph: '🏏', age: '8–15 yrs', when: 'Tue–Thu–Sat · 6 AM', price: 4800, venue: 'Dadar Shivaji Park', ratio: 'Ex–Ranji coaches', tint: 42, desc: 'Net sessions with certified helmets, bowling-machine work and video feedback every month.' },
    { id: 'g4', title: 'Basketball Academy', glyph: '🏀', age: '9–16 yrs', when: 'Tue–Thu · 6 PM', price: 4200, venue: 'Powai Court', ratio: 'FIBA-certified', tint: 24, desc: 'Ball-handling, shooting mechanics and 3v3 league play indoors, monsoon-proof.' },
    { id: 'g5', title: 'Swimming Programs', glyph: '🏊', age: '4–12 yrs', when: 'Daily batches · 7 AM', price: 5500, venue: 'Powai heated pool', ratio: '1:4 in water', tint: 205, desc: 'From first splash to lap-swimmer levels, with in-water coaches at all times.' },
    { id: 'g6', title: 'Tennis Development', glyph: '🎾', age: '5–13 yrs', when: 'Tue–Sat · 4 PM', price: 4600, venue: 'Bandra courts', ratio: 'Red/Orange/Green stages', tint: 120, desc: 'ITF Play&amp;Stay method with low-compression balls so rallies happen in week one.' },
    { id: 'g7', title: 'Martial Arts Dojo', glyph: '🥋', age: '5–14 yrs', when: 'Mon–Fri · 5 PM', price: 3800, venue: 'Andheri dojo', ratio: 'Black-belt instructors', tint: 0, desc: 'Karate and judo tracks with belt gradings, anti-bullying confidence modules and full sparring-safety policy.' },
    { id: 'g8', title: 'Athletics Club', glyph: '🏃', age: '8–16 yrs', when: 'Sat–Sun · 6:30 AM', price: 3600, venue: 'Khar track', ratio: 'AAF-certified', tint: 140, desc: 'Run-jump-throw mechanics, first meet preparation and age-correct conditioning.' },
    { id: 'g9', title: 'Girls’ Confidence Program', glyph: '💪', age: '9–14 yrs', when: 'Wed · 5 PM', price: 2800, venue: 'Powai studio', ratio: 'Female-led', tint: 16, desc: 'Six-week movement and mentorship circle. Body confidence without any appearance scoring.' },
    { id: 'g10', title: 'Inclusive & Adaptive Sessions', glyph: '♿', age: 'All ages', when: 'Sun · 10 AM', price: 2500, venue: 'Powai & home visits', ratio: '1:2 ratio, therapists on call', tint: 200, desc: 'Adapted sports for children with physical, sensory and neurodevelopmental needs. Every session plan is individualised.' },
    { id: 'g11', title: 'Teen Athlete Development', glyph: '🏆', age: '13–17 yrs', when: 'Mon–Fri · 6 AM', price: 5200, venue: 'Khar strength lab', ratio: 'SSC-certified S&C', tint: 40, desc: 'Age-appropriate strength, speed and recovery education — effort-based praise only, no weight-cut culture.' },
    { id: 'g12', title: 'Coach Certification (Partner)', glyph: '🎓', age: 'Adults 18+', when: 'Quarterly cohorts', price: 9500, venue: 'Blended + Mumbai campus', ratio: 'NSNCA-aligned', tint: 220, desc: 'First-aid, safeguarding and age-group pedagogy certification for aspiring NextPlay coaches.' }
  ];

  var CAMPS = [
    { id: 'c1', title: 'Summer Multi-Sport Camp', glyph: '☀️', date: 'Apr 20 – May 29', when: 'Mon–Fri · 9 AM–1 PM', age: '5–12 yrs', price: 6500, venue: 'Powai campus', seats: '24 seats · batch', tint: 48, desc: 'Ten sports in ten days, splash pool time and a parents’ showcase on the final Friday.' },
    { id: 'c2', title: 'Diwali Football Bootcamp', glyph: '🪔', date: 'Nov 2 – Nov 7', when: 'Daily · 8–11 AM', age: '8–14 yrs', price: 3200, venue: 'Andheri turf', seats: '32 seats · batch', tint: 210, desc: 'Six mornings of technical work ending in a floodlit mini-tournament.' },
    { id: 'c3', title: 'Weekend Junior Tournaments', glyph: '🏆', date: 'Last Sunday monthly', when: '9 AM–2 PM', age: '7–15 yrs', price: 800, venue: 'Rotating venues', seats: 'Team entries', tint: 40, desc: 'Football, cricket and basketball cups with certified officials and safety kits on site.' },
    { id: 'c4', title: 'Birthday Sports Party', glyph: '🎂', date: 'Any weekend slot', when: '2-hour party', age: '4–12 yrs', price: 12000, venue: 'Your society ground / our turf', seats: 'Up to 20 kids', tint: 340, desc: 'Coaches arrive with the full games kit, medals for every guest and a cake-cutting break.' },
    { id: 'c5', title: 'Parent–Child Play Saturdays', glyph: '👨‍👩‍👧', date: 'Every 2nd Saturday', when: '4–6 PM', age: '2–7 yrs + parent', price: 1200, venue: 'Powai campus', seats: '15 families', tint: 200, desc: 'Unstructured joy: obstacle courses, parachute games and parent-vs-kid relays.' },
    { id: 'c6', title: 'Monsoon Indoor Games Week', glyph: '🌧️', date: 'Jul 13 – Jul 18', when: 'Mon–Fri · 10 AM', age: '4–10 yrs', price: 2800, venue: 'Powai indoor arena', seats: '20 seats · batch', tint: 220, desc: 'Gymnastics, table tennis, dance and indoor obstacle courses while it pours outside.' },
    { id: 'c7', title: 'Trek & Nature Adventure Camp', glyph: '🏕️', date: 'Dec 21 – Dec 24', when: '3-day residential', age: '9–15 yrs', price: 11500, venue: 'Lonavala', seats: '40 seats', tint: 140, desc: 'Ropes, trekking, campfire and star-gazing with certified outdoor first-aid staff.' },
    { id: 'c8', title: 'Adaptive Sports Fun Day', glyph: '♿', date: 'Oct 5', when: '10 AM–1 PM', age: 'All ages', price: 500, venue: 'Powai campus', seats: 'Open to all', tint: 190, desc: 'Free inclusive festival with boccia, seated volleyball and sensory-friendly zones.' }
  ];

  var QUIZ_QUESTIONS = [
    { q: 'What is the child’s age?', key: 'age', opts: [['2–4', '🧒', 'tiny'], ['5–7', '🏃', 'little'], ['8–11', '🤾', 'rising'], ['12–14', '🏅', 'young'], ['15–17', '🏆', 'future']] },
    { q: 'What excites them most?', key: 'interest', opts: [['Team games', '🤝', 'team'], ['Solo challenge', '🎯', 'solo'], ['Creative movement', '💃', 'creative'], ['Speed & races', '⚡', 'fast'], ['Outdoors & nature', '🏕️', 'outdoors'], ['Strategy & focus', '🧠', 'strategy'], ['Strength & power', '💪', 'strength'], ['Water & swimming', '🌊', 'water']] },
    { q: 'How experienced are they?', key: 'exp', opts: [['Total beginner', '🌱', 'beginner'], ['Played a bit', '⚽', 'intermediate'], ['Trains regularly', '🔥', 'advanced']] },
    { q: 'How much time weekly?', key: 'time', opts: [['1–2 hours', '🕐', 'light'], ['3–5 hours', '🕑', 'medium'], ['6+ hours', '🕒', 'serious']] },
    { q: 'Monthly budget for play?', key: 'budget', opts: [['Under ₹2,000', '🪙', 'low'], ['₹2,000–5,000', '💵', 'mid'], ['₹5,000+', '💎', 'high']] }
  ];

  window.NPD = {
    SPORTS: SPORTS,
    PRODUCTS: PRODUCTS,
    CATS: CATS,
    AGES: AGES,
    PROGRAMS: PROGRAMS,
    CAMPS: CAMPS,
    QUIZ: QUIZ_QUESTIONS,
    money: function (n) { return '₹' + Number(n).toLocaleString('en-IN'); }
  };
})();